scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: user-service
    scrape_interval: 15s
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: product-service
    scrape_interval: 15s
    static_configs:
      - targets: ["product-service:8000"]

  - job_name: cart-service
    scrape_interval: 15s
    static_configs:
      - targets: ["cart-service:8000"]

  - job_name: search-service
    scrape_interval: 15s
    static_configs:
      - targets: ["search-service:8000"]
