# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\x1a\x1cgoogle/protobuf/struct.proto\"\xb6\x01\n\x10SendEmailRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.notification.EmailType\x12>\n\x08metadata\x18\x03 \x03(\x0b\x32,.notification.SendEmailRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x11SendEmailResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t*\x92\x01\n\tEmailType\x12\x1a\n\x16\x45MAIL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x45MAIL_TYPE_WELCOME\x10\x01\x12\x1d\n\x19\x45MAIL_TYPE_PASSWORD_RESET\x10\x02\x12\x15\n\x11\x45MAIL_TYPE_VERIFY\x10\x03\x12\x1b\n\x17\x45MAIL_TYPE_NOTIFICATION\x10\x04\x32\x63\n\x13NotificationService\x12L\n\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x1f.notification.SendEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDEMAILREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SENDEMAILREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EMAILTYPE']._serialized_start=305
  _globals['_EMAILTYPE']._serialized_end=451
  _globals['_SENDEMAILREQUEST']._serialized_start=67
  _globals['_SENDEMAILREQUEST']._serialized_end=249
  _globals['_SENDEMAILREQUEST_METADATAENTRY']._serialized_start=202
  _globals['_SENDEMAILREQUEST_METADATAENTRY']._serialized_end=249
  _globals['_SENDEMAILRESPONSE']._serialized_start=251
  _globals['_SENDEMAILRESPONSE']._serialized_end=302
  _globals['_NOTIFICATIONSERVICE']._serialized_start=453
  _globals['_NOTIFICATIONSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
