# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: price.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'price.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprice.proto\x12\x05price\"\"\n\x0cPriceRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"\x1e\n\rPriceResponse\x12\r\n\x05price\x18\x02 \x01(\x02\x32\x45\n\x0cPriceService\x12\x35\n\x08GetPrice\x12\x13.price.PriceRequest\x1a\x14.price.PriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'price_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=22
  _globals['_PRICEREQUEST']._serialized_end=56
  _globals['_PRICERESPONSE']._serialized_start=58
  _globals['_PRICERESPONSE']._serialized_end=88
  _globals['_PRICESERVICE']._serialized_start=90
  _globals['_PRICESERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
